export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const RECEIVE_ROBOTS_SUCCESS = 'RECEIVE_ROBOTS_SUCCESS';
export const RECEIVE_ROBOTS_FAILED = 'RECEIVE_ROBOTS_FAILED';
